### PR TITLE
sample localization structure

### PR DESCRIPTION
**Pull request by apisit**
- Add zh i18n

### CODE REVIEW

**Comment by apisit** [comment]
@Celia18305 I fixed a few places for you as an example to it to build successfully. Basically you would need `` for things that looks like a html syntax `<this>`

```code
e.g. <ECPoint> becomes  `<ECPoint>`
```

**Comment by Celia18305** [comment]
@apisit I checked and found no further issues. Let me know if there is anything I can do.

**Comment by apisit** [comment]
Thanks, @Celia18305 
How about the menu titles? Should they be in Chinese too? 

image

**Comment by Celia18305** [comment]
@apisit To translate the menu titles, which file should I edit?

**Comment by apisit** [comment]
@Celia18305 You can control menu title and its index by adding the following code below to the first line of every MD file.

```
---
sidebar_label: 'Overview'
sidebar_position: 0
---
```
Example [here](https://raw.githubusercontent.com/neo-project/neo-dev-portal/dev/docs/n3/fees.md)


There is also a `_category.json` file which is used to control the category menu title.

You can see examples from [here](https://github.com/neo-project/neo-dev-portal/tree/dev/docs/n3/develop)

**Comment by Celia18305** [comment]
@apisit I have updated menu titles in zh folder with reference to the corresponding English set. Let me know if anyting missing.

**Pull request merged**
